### ISSUE TITLE
论文地址

### ISSUE THREAD

**Issue by guoliangq** [ming71/GCIoU-loss#1]
您可以上传一下论文嘛，因为我在网上并没有找到您的论文，但我非常感兴趣

**Comment by ming71** [comment]
感谢您的关注，论文在这里放出来了https://openaccess.thecvf.com/content/CVPR2023/html/Ming_Deep_Dive_Into_Gradients_Better_Optimization_for_3D_Object_Detection_CVPR_2023_paper.html
